# Generated by Django 2.2.17 on 2020-12-28 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201228_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='followup1',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='followup2',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='followup3',
            field=models.DateTimeField(blank=True),
        ),
    ]
