# Generated by Django 2.2.17 on 2020-12-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20201228_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='followup1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='followup2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='followup3',
            field=models.DateField(blank=True, null=True),
        ),
    ]
