# Generated by Django 2.2.17 on 2020-12-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_date_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='response',
            field=models.CharField(choices=[('No response', 'No response'), ('In-progress', 'In-progress'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='No response', max_length=15, null=True),
        ),
    ]
