# Generated by Django 2.2.17 on 2020-12-28 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20201228_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Contact'),
        ),
    ]
