# Generated by Django 2.2.17 on 2020-12-28 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20201228_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='jobs.Job'),
        ),
    ]
