# Generated by Django 2.2.17 on 2020-12-28 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20201228_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='job',
        ),
    ]
